server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saritaksharma/spring-cloud-config-server
          search-paths:
           - '*service'












